# Promise 输出
## 2. 函数提升

```js
foo();
var foo;
function foo(){
  console.log(1);
}
foo = function(){
  console.log(2);
}
```
输出：`1`
解释：
函数提升：
只提升 函数声明，而不会提升函数表达式

## 5. promise.finally

```js
const p1 = new Promise((resolve) => {
  setTimeout(() => {
    resolve('resolve3');
    console.log('timer1')
  }, 0)
  resolve('resovle1');
  resolve('resolve2');
}).then(res => {
  console.log(res)
  setTimeout(() => {
    console.log(p1)
  }, 1000)
}).finally(res => {
  console.log('finally', res)
})

```
输出：
'resolve1'
'finally' undefined
'timer1'
Promise{<resolved>: undefined}

解释：
![20220729225241](https://xd-imgsubmit.oss-cn-beijing.aliyuncs.com/images/20220729225241.png)

## 6. .then()穿透

```js
const async1 = async () => {
  console.log('async1');
  setTimeout(() => {
    console.log('timer1')
  }, 2000)
  await new Promise(resolve => {
    console.log('promise1')
  })
  console.log('async1 end')
  return 'async1 success'
} 
console.log('script start');
async1().then(res => console.log(res));
console.log('script end');
Promise.resolve(1)
  .then(2)
  .then(Promise.resolve(3))
  .catch(4)
  .then(res => console.log(res))
setTimeout(() => {
  console.log('timer2')
}, 1000)

```
结果：
![20220731110048](https://xd-imgsubmit.oss-cn-beijing.aliyuncs.com/images/20220731110048.png)
解析：
await 紧跟在后面的语句立即执行，下面的语句会成为一个微任务， 当 await的结果为 真或者是 resolved之后执行，如果后面跟着一个pending状态的promise，那么后面的微任务就会一直不执行
![20220731110249](https://xd-imgsubmit.oss-cn-beijing.aliyuncs.com/images/20220731110249.png)

## 7. promise 第38题

```js
const first = () => (new Promise((resolve, reject) => {
    console.log(3);
    let p = new Promise((resolve, reject) => {
        console.log(7);
        setTimeout(() => {
            console.log(5);
            resolve(6);
            console.log(p)
        }, 0)
        resolve(1);
    });
    resolve(2);
    p.then((arg) => {
        console.log(arg);
    });
}));
first().then((arg) => {
    console.log(arg);
});
console.log(4);


```
输出：
![20220731111348](https://xd-imgsubmit.oss-cn-beijing.aliyuncs.com/images/20220731111348.png)
解释：

![20220731111406](https://xd-imgsubmit.oss-cn-beijing.aliyuncs.com/images/20220731111406.png)

## 8. try/ catch 与事件循环

```js
async function async1 () {
    try {
      await Promise.reject('error!!!')
    } catch(e) {
      console.log(e)
    }
    console.log('async1');
    return Promise.resolve('async1 success')
  }
  async1().then(res => console.log(res))
  console.log('script start')

```
答案：
![20220731112742](https://xd-imgsubmit.oss-cn-beijing.aliyuncs.com/images/20220731112742.png)

try /catch为同步执行的代码。
await为让出当前线程的标志，遇到await之后，执行 Promise.reject(); 让出线程 执行 `log(script start)`

## 13. await之后的执行吗？

```js
async function async1 () {
  console.log('async1 start');
  await new Promise(resolve => {
    console.log('promise1')
  })
  console.log('async1 success');
  return 'async1 end'
}
console.log('srcipt start')
async1().then(res => console.log(res))
console.log('srcipt end')

```

输出：

![20220731122044](https://xd-imgsubmit.oss-cn-beijing.aliyuncs.com/images/20220731122044.png)

## 18. Promise.race()

```js
function runAsync(x) {
    const p = new Promise(r =>
        setTimeout(() => r(x, console.log(x)), 1000)
    );
    return p;
}

function runReject(x) {
    const p = new Promise((res, rej) =>
        setTimeout(() => rej(`Error: ${x}`, console.log(x)), 1000 * x)
    );
    return p;
}
Promise.race([runReject(0), runAsync(1), runAsync(2), runAsync(3)])
    .then(res => console.log("result: ", res))
    .catch(err => console.log(err));
```

结果：

.race()的作用也是接收一组异步任务，然后并行执行异步任务，只保留取第一个执行完成的异步操作的结果，其他的方法仍在执行，不过执行结果会被抛弃。

![20220731123311](https://xd-imgsubmit.oss-cn-beijing.aliyuncs.com/images/20220731123311.png)

## 19. Promise.all()  reject

```js

function runAsync (x) {
  const p = new Promise(r => setTimeout(() => r(x, console.log(x)), 1000))
  return p
}
function runReject (x) {
  const p = new Promise((res, rej) => setTimeout(() => rej(`Error: ${x}`, console.log(x)), 1000 * x))
  return p
}
Promise.all([runAsync(1), runReject(4), runAsync(3), runReject(2)])
  .then(res => console.log(res))
  .catch(err => console.log(err))

```

输出：

![20220731123654](https://xd-imgsubmit.oss-cn-beijing.aliyuncs.com/images/20220731123654.png)

## 21. 微任务的排序

```js

function promise1 () {
  let p = new Promise((resolve) => {
    console.log('promise1');
    resolve('1')
  })
  return p;
}
function promise2 () {
  return new Promise((resolve, reject) => {
    reject('error')
  })
}
promise1()
  .then(res => console.log(res))
  .catch(err => console.log(err))
  .finally(() => console.log('finally1'))

promise2()
  .then(res => console.log(res))
  .catch(err => console.log(err))
  .finally(() => console.log('finally2'))

```
![20220731145214](https://xd-imgsubmit.oss-cn-beijing.aliyuncs.com/images/20220731145214.png)

## 22. finally()的返回值

```js
Promise.resolve('1')
  .then(res => {
    console.log(res)
  })
  .finally(() => {
    console.log('finally')
  })
Promise.resolve('2')
  .finally(() => {
    console.log('finally2')
  	return '我是finally2返回的值'
  })
  .then(res => {
    console.log('finally2后面的then函数', res)
  })

```
finally()的返回值为上一个  Promise对象的值，如果抛出异常则返回异常的Promise对象

![20220731150200](https://xd-imgsubmit.oss-cn-beijing.aliyuncs.com/images/20220731150200.png)

## 26. .then() .catch()返回的值

```js
const promise = Promise.resolve().then(() => {
  return promise;
})
promise.catch(console.err)
```
`.then()`和`.catch()`的值不能为 promise本身，否则会造成死循环， 因此结果会报错

`： TypeError: chaing sycle detected for promise`

## 包裹非promise对象

```js
Promise.resolve().then(() => {
  return new Error('error!!!')
}).then(res => {
  console.log("then: ", res)
}).catch(err => {
  console.log("catch: ", err)
})
```
注意：
非promise类型的值会被包裹程promise对象的值，相当于调用`Promise.resolve(new Error("error~!!!"))` 并非抛出了一个错误

抛出错误的正确方法为：
`return Promise.reject(new Error('error！！！'))`
或者：
`throw new Error()`

# 其他输出题目

## 冒泡 目标捕获

## 数组赋值

```js
let person = { name: "Lydia" }; 
// let person = "linda"
const members = [person]; // 将member[0]指向 person

person = null;

console.log(members);
```

## 函数.length 

一道非常经典的面试题

123[‘toString‘].length + 123 ？

123 是一个数值， 其本身是没有`[toString]`, 
沿着原型链 找到 Number原型对象上的方法身上的该方法, Numer的原型对象上的toString()
函数的`length`值为 第一具有默认值之前的形参的个数

> 第一个具有默认值之前的参数个数;length 是函数对象的一个属性值，指该函数有多少个必须要传入的参数，即形参的个数。
形参的数量不包括剩余参数个数，仅包括第一个具有默认值之前的参数个数。

![20220731185845](https://xd-imgsubmit.oss-cn-beijing.aliyuncs.com/images/20220731185845.png)

具有一个形参个数，表示数字 到字符串转换的基数； 所以 `.length`为1

## NaN

not a Number 
`typeOf NaN === "number"`

## 改造定时器

非常经典的面试题aa

```js
for(var i = 1; i <= 5; i ++){ setTimeout(function timer(){ console.log(i) }, 0) }
```
上述代码会输出什么？
输出 5个6，原因是什么？
js的异步执行机制：setTimeout为宏任务， 异步执行，只用同步任务执行完毕之后才会去执行 宏任务；

`var`声明的变量为全局变量， 每次i的变化 会影响到之前的值；

改造：

使用 `let`关键字， 创建对应的块级作用域，每一个宏任务中的i相互独立；

```js
for(let i = 1; i <= 5; i++){
  setTimeout(function timer(){
 	 console.log(i)
  },0)
}

```
2. 立即执行函数
使用函数作用域，和立即执行函数，创建一个单独的作用域，每次输出的j在当前的函数作用域内，且每一个值不相等
```js
for(var i = 1;i <= 5;i++){
  (function(j){
    setTimeout(function timer(){
    	console.log(j)
    }, 0)
  })(i)
}

```
3. 使用定时器的第三个参数
![20220731191511](https://xd-imgsubmit.oss-cn-beijing.aliyuncs.com/images/20220731191511.png)

```js
for(var i=1;i<=5;i++){
  setTimeout(function timer(j){
  	console.log(j)
  }, 0, i)
}
```

轮到 每一个定时器时，都将对应的参数传入到function中去

##  let const 和var的变量提升

```js

function sayHi() {
  console.log(name)
  console.log(age)
  var name = 'Lydia'
  let age = 21
}

sayHi()
```
输出：`undefined `和referrenceError

![20220731191920](https://xd-imgsubmit.oss-cn-beijing.aliyuncs.com/images/20220731191920.png)

## fromEntries的使用

![20220731192831](https://xd-imgsubmit.oss-cn-beijing.aliyuncs.com/images/20220731192831.png)

```js
const keys = ["name", "age"]
const values = ["Lydia", 22]

const method = /* ?? */
Object[method](keys.map((_, i) => {
	return [keys[i], values[i]]
})) // { name: "Lydia", age: 22 }
```

首先 keys.map(), 会得到一个二维数组，然后 在使用fromEntries将其转换为对象 
## 148. IIFE块级作用域
```js
(() => {
  let x = (y = 10);
})();

console.log(typeof x);
console.log(typeof y);
```

![20220816225448](https://xd-imgsubmit.oss-cn-beijing.aliyuncs.com/images/20220816225448.png)
## 158 try catch的块级作用域
```js
(() => {
  let x, y
  try {
    throw new Error()
  } catch (x) {
    (x = 1), (y = 2)
    console.log(x)
  }
  console.log(x)
  console.log(y)
})()
```
输出：
![20220816224533](https://xd-imgsubmit.oss-cn-beijing.aliyuncs.com/images/20220816224533.png)
## 161. 对象的键值为字符串

```js
const a = {}
const b = { key: 'b' }
const c = { key: 'c' }

a[b] = 123
a[c] = 456

console.log(a[b])
```

![20220816224021](https://xd-imgsubmit.oss-cn-beijing.aliyuncs.com/images/20220816224021.png)
## 167 ...args
```js
function getAge(...args) {
  console.log(typeof args)
}

getAge(21)
```
结果：

![20220816223026](https://xd-imgsubmit.oss-cn-beijing.aliyuncs.com/images/20220816223026.png)
## 169 模板字面量

```js

function getPersonInfo(one, two, three) {
  console.log(one)
  console.log(two)
  console.log(three)
}

const person = 'Lydia'
const age = 21

getPersonInfo`${person} is ${age} years old`
```